HOOKS["InitPostEntity"] = function()
	ents.FindByClass("trigger_changelevel")[1]:SetKeyValue("StartDisabled", "1")
	ents.FindByClass("weapon_357")[1]:Remove()
	ents.FindByName("relay_combineshieldwall&i_on4")[1]:Fire("AddOutput","OnTrigger tm_shieldtrigger,Enable,,1,1",0)
	ents.FindByName("relay_combineshieldwall&i_on4")[1]:Fire("AddOutput","OnTrigger fb_surprisemothafocka,Kill,,1,1",0)
	ents.FindByName("relay_combineshieldwall&i_on4")[1]:Fire("AddOutput","OnTrigger ee1,Explode,,1,1",0)
	ents.FindByName("relay_combineshieldwall&i_on4")[1]:Fire("AddOutput","OnTrigger pt_combinespawnerest1,ForceSpawn,,1,1",0)
	ents.FindByName("relay_combineshieldwall&i_on4")[1]:Fire("AddOutput","OnTrigger ag_song28,PlaySound,,1.5,1",0)
	ents.FindByName("relay_combineshieldwall&i_on4")[1]:Fire("AddOutput","OnTrigger pt_combinespawnerest2,ForceSpawn,,7,1",0)
	ents.FindByName("relay_combineshieldwall&i_on4")[1]:Fire("AddOutput","OnTrigger pt_combinespawnerest3,ForceSpawn,,16,1",0)
	ents.FindByName("hurt_combineshieldwall&i4")[1]:Remove()
	ents.FindByName("trigger_combineshieldwall&i4")[1]:Remove()
	ents.FindByName("brush_combineshieldwall&i4")[1]:Remove()
	ents.FindByName("clip_combineshieldwall&i4")[1]:Remove()
	ents.FindByName("sound_combineshieldwall_idle&i4")[1]:Remove()
	ents.FindByName("fp_hook1")[1]:SetKeyValue("spawnflags", "2703361")
	ents.FindByName("fp_hook2")[1]:SetKeyValue("spawnflags", "2703361")
	ents.FindByName("fd_metaldoor6")[1]:Fire("AddOutput","OnClose cp1,SetAsCP,,0,1",0)
	ents.FindByName("lr_trainstart1")[1]:Fire("AddOutput","OnTrigger cp3,SetAsCP,,26,1",0)
	ents.FindByName("fd_metaldoor8")[1]:Fire("AddOutput","OnFullyClosed cp5,SetAsCP,,0,1",0)
	ents.FindByName("fd_metaldoor9")[1]:Fire("AddOutput","OnClose cp6,SetAsCP,,0,1",0)
	ents.FindByName("fd_metaldoor10")[1]:Fire("AddOutput","OnFullyClosed cp7,SetAsCP,,0,1",0)
	ents.FindByName("fd_lift")[1]:Fire("AddOutput","OnFullyOpen cp8,SetAsCP,,0,1",0)
	
	local cp1 = ents.Create("coop_checkpoint")
	cp1:SetKeyValue("targetname", "cp1")
	cp1:SetKeyValue("updatecp", "1")
	cp1:SetKeyValue("radius", "0")
	cp1:SetKeyValue("moveplayers", "1")
	cp1:SetKeyValue("Angles", "0 315 0")
	cp1:SetKeyValue("Origin", "2144 -2144 -119")
    cp1:Spawn()
	
	local cp2 = ents.Create("coop_checkpoint")
	cp2:SetKeyValue("targetname", "cp2")
	cp2:SetKeyValue("updatecp", "1")
	cp2:SetKeyValue("radius", "128")
	cp2:SetKeyValue("moveplayers", "1")
	cp2:SetKeyValue("Angles", "0 0 0")
	cp2:SetKeyValue("Origin", "-11517 10827 832")
    cp2:Spawn()
	
	local cp3 = ents.Create("coop_checkpoint")
	cp3:SetKeyValue("targetname", "cp3")
	cp3:SetKeyValue("updatecp", "1")
	cp3:SetKeyValue("radius", "0")
	cp3:SetKeyValue("moveplayers", "0")
	cp3:SetKeyValue("Angles", "0 0 0")
	cp3:SetKeyValue("Origin", "-9375 10659 925")
    cp3:Spawn()
	
	local cp4 = ents.Create("coop_checkpoint")
	cp4:SetKeyValue("targetname", "cp4")
	cp4:SetKeyValue("updatecp", "1")
	cp4:SetKeyValue("radius", "100")
	cp4:SetKeyValue("moveplayers", "0")
	cp4:SetKeyValue("Angles", "0 0 0")
	cp4:SetKeyValue("Origin", "2979 -2021 -119")
    cp4:Spawn()
	
	local cp5 = ents.Create("coop_checkpoint")
	cp5:SetKeyValue("targetname", "cp5")
	cp5:SetKeyValue("updatecp", "1")
	cp5:SetKeyValue("radius", "0")
	cp5:SetKeyValue("moveplayers", "1")
	cp5:SetKeyValue("Angles", "0 90 0")
	cp5:SetKeyValue("Origin", "3223 -1706 -119")
    cp5:Spawn()
	
	local cp6 = ents.Create("coop_checkpoint")
	cp6:SetKeyValue("targetname", "cp6")
	cp6:SetKeyValue("updatecp", "1")
	cp6:SetKeyValue("radius", "0")
	cp6:SetKeyValue("moveplayers", "1")
	cp6:SetKeyValue("Angles", "0 224 0")
	cp6:SetKeyValue("Origin", "2069 -1383 -119")
    cp6:Spawn()
	
	local cp7 = ents.Create("coop_checkpoint")
	cp7:SetKeyValue("targetname", "cp7")
	cp7:SetKeyValue("updatecp", "1")
	cp7:SetKeyValue("radius", "0")
	cp7:SetKeyValue("moveplayers", "1")
	cp7:SetKeyValue("Angles", "0 270 0")
	cp7:SetKeyValue("Origin", "1422 -2154 -119")
    cp7:Spawn()
	
	local cp8 = ents.Create("coop_checkpoint")
	cp8:SetKeyValue("targetname", "cp8")
	cp8:SetKeyValue("updatecp", "1")
	cp8:SetKeyValue("radius", "0")
	cp8:SetKeyValue("moveplayers", "1")
	cp8:SetKeyValue("Angles", "0 270 0")
	cp8:SetKeyValue("Origin", "1704 -4040 1482")
    cp8:Spawn()
	
end