HOOKS["InitPostEntity"] = function()
	ents.FindByName("trainstation_armory_equip")[1]:Remove()
	local equip = ents.Create("game_player_equip")
	equip:SetName("trainstation_armory_equip")
	equip:SetKeyValue("item_box_sniper_rounds", "1")
	equip:SetKeyValue("item_box_buckshot", "1")
	equip:SetKeyValue("item_ammo_smg1_large", "1")
	equip:SetKeyValue("item_ammo_pistol_large", "1")
	equip:SetKeyValue("item_ammo_ar2_large", "1")
	equip:SetKeyValue("item_ammo_357_large", "1")
	equip:Spawn()
	
	ents.FindByName("trainstation_sewer_equip")[1]:Remove()
	equip = ents.Create("game_player_equip")
	equip:SetName("trainstation_sewer_equip")
	equip:SetKeyValue("item_box_buckshot", "1")
	equip:SetKeyValue("item_ammo_smg1_large", "1")
	equip:SetKeyValue("item_ammo_pistol_large", "1")
	equip:SetKeyValue("item_ammo_ar2_large", "1")
	equip:Spawn()
end